### ISSUE TITLE
program crashes using cut or copy without marked string

### ISSUE THREAD

**Issue by linjin** [janhaag/PSE2011#25]

**Comment by tschlum** [comment]
Fixed in e5a821b70fc6dd7d7d629813e5f0a1d0d0037404.

**Comment by linjin** [comment]
program still crashes when you type a random string and then use cut/copy without marked string
